services:
  go:
    build: 
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go-api
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/go/src/app
  mysql:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
     - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307
    command: --port 3307
    links:
     - go
  react:
    build: 
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd todoapp && npm start"
    ports:
     - "3000:3000"
    stdin_open: true
    