CREATE SCHEMA IF NOT EXISTS tododb;
USE tododb;
DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT  EXISTS todos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO todos (title) VALUES ("お洗濯");